"""Synthetic-safe, side-effect-free result reporting contracts."""

# Re-export the input validation types at the reporting boundary so callers
# can construct a complete typed report contract from one import.
from febio_cae_harness.solver import (  # noqa: E402
    FbsValidation,
    LogValidation,
    SolverClassification,
    SolverRunResult,
    SolverState,
)

from .authority import ReportAuthority, ReportAuthorityManager
from .gates import (
    SuccessGate,
    evaluate_result_success,
    evaluate_success,
    evaluate_success_gate,
    evaluate_success_gates,
)
from .report import (
    ReportAssembler,
    ReportBuilder,
    assemble_report,
    assemble_result_report,
    build_report,
)
from .types import (
    AssembledReport,
    AttemptIdentity,
    EvaluationEvidence,
    EvidenceKind,
    EvidenceProvenance,
    EvidenceRef,
    EvidenceReference,
    EvidenceReferences,
    FreshnessValidation,
    FreshOutputValidation,
    GateEvaluation,
    JacobianEvidence,
    MeshEvidence,
    OutputFreshness,
    OutputFreshValidation,
    Report,
    ReportAssembly,
    ReportEvidence,
    ReportEvidenceReference,
    ReportProvenance,
    ResultEvidence,
    ResultOutputValidation,
    ResultReport,
    RoiEvidence,
    SuccessGateEvaluation,
    SuccessGateResult,
)

__all__ = [
    "AssembledReport",
    "AttemptIdentity",
    "EvidenceKind",
    "EvidenceProvenance",
    "EvidenceRef",
    "EvidenceReference",
    "EvidenceReferences",
    "EvaluationEvidence",
    "FbsValidation",
    "FreshOutputValidation",
    "FreshnessValidation",
    "GateEvaluation",
    "JacobianEvidence",
    "LogValidation",
    "MeshEvidence",
    "OutputFreshValidation",
    "OutputFreshness",
    "Report",
    "ReportAuthority",
    "ReportAuthorityManager",
    "ReportAssembler",
    "ReportAssembly",
    "ReportBuilder",
    "ReportEvidence",
    "ReportEvidenceReference",
    "ReportProvenance",
    "ResultEvidence",
    "ResultOutputValidation",
    "ResultReport",
    "RoiEvidence",
    "SolverClassification",
    "SolverRunResult",
    "SolverState",
    "SuccessGate",
    "SuccessGateEvaluation",
    "SuccessGateResult",
    "assemble_report",
    "assemble_result_report",
    "build_report",
    "evaluate_result_success",
    "evaluate_success",
    "evaluate_success_gate",
    "evaluate_success_gates",
]
