"""Build deployment and headless launch planning APIs."""

from .deployment import (
    BUILD_IDENTITY_NAME,
    DEPLOYMENT_LOCK_NAME,
    LATEST_DIRECTORY_NAME,
    LAUNCHER_NAME,
    PRODUCT_DIRECTORY_NAME,
    ROLLBACK_DIRECTORY_NAME,
    STAGING_DIRECTORY_NAME,
    AtomicDeployer,
    BuildIdentity,
    DeploymentError,
    DeploymentLayout,
    DeploymentManager,
    DeploymentReceipt,
    DeploymentRollbackError,
    compute_payload_sha256,
    deployment_layout,
    deployment_lock,
    stage_latest_development,
    verify_payload_identity,
)
from .planner import LaunchError, LaunchPlan, launch_cli, plan_cli_launch, read_build_identity
from .shortcut import (
    SHORTCUT_DESCRIPTOR_NAME,
    SHORTCUT_DISPLAY_NAME,
    SHORTCUT_LINK_NAME,
    START_MENU_RELATIVE_PATH,
    ShortcutDescriptor,
    ShortcutDescriptorManager,
    ShortcutManager,
    default_start_menu_root,
    fixed_shortcut_descriptor,
    shortcut_descriptor,
    write_shortcut_descriptor,
)

__all__ = [
    "AtomicDeployer",
    "BUILD_IDENTITY_NAME",
    "BuildIdentity",
    "compute_payload_sha256",
    "DEPLOYMENT_LOCK_NAME",
    "DeploymentError",
    "DeploymentLayout",
    "DeploymentManager",
    "DeploymentReceipt",
    "DeploymentRollbackError",
    "LAUNCHER_NAME",
    "LATEST_DIRECTORY_NAME",
    "LaunchError",
    "LaunchPlan",
    "PRODUCT_DIRECTORY_NAME",
    "ROLLBACK_DIRECTORY_NAME",
    "SHORTCUT_DESCRIPTOR_NAME",
    "SHORTCUT_DISPLAY_NAME",
    "SHORTCUT_LINK_NAME",
    "START_MENU_RELATIVE_PATH",
    "STAGING_DIRECTORY_NAME",
    "ShortcutDescriptor",
    "ShortcutDescriptorManager",
    "ShortcutManager",
    "default_start_menu_root",
    "deployment_lock",
    "deployment_layout",
    "fixed_shortcut_descriptor",
    "launch_cli",
    "plan_cli_launch",
    "read_build_identity",
    "shortcut_descriptor",
    "stage_latest_development",
    "verify_payload_identity",
    "write_shortcut_descriptor",
]
