"""P1-A domain contract foundations owned by the common-contract worker."""

from .budget import Budget, BudgetValidationError
from .canonical import SCHEMA_VERSION, CanonicalizationError, canonical_bytes
from .contact import (
    ArrangementIntent,
    AsPlaced,
    ContactId,
    ContactIntent,
    ContactValidationError,
    CoulombFriction,
    FrictionIntent,
    Frictionless,
    SpecifiedGap,
)
from .evidence import SUPPORTED_SOURCE_KINDS, EvidenceRef
from .geometry import GeometryIntent, GeometryValidationError
from .material import (
    CompressibleNeoHookean,
    IsotropicLinearElastic,
    MaterialApplicability,
    MaterialCandidate,
    MaterialValidationError,
)
from .mesh_policy import (
    LocalRefinement,
    MeshPolicy,
    MeshPolicyValidationError,
    NumericalProfileRef,
)
from .motion import MotionApplicability, MotionProfile, MotionSample, MotionValidationError
from .output_policy import (
    EvaluationRequest,
    OutputPolicy,
    OutputPolicyValidationError,
    OutputRequest,
)
from .rigid import RigidPrimitive, RigidValidationError
from .rigid_kinematics import (
    DofComponent,
    DofSpecification,
    DofState,
    KinematicCompatibility,
    MotionCompatibility,
    RigidDOFComponent,
    RigidDofComponent,
    RigidDOFSpecification,
    RigidDofSpecification,
    RigidDOFState,
    RigidDofState,
    RigidKinematicsValidationError,
    RigidToolIntent,
    check_motion_compatibility,
    check_translational_indentation_compatibility,
    validate_translational_indentation_compatibility,
)
from .selection import (
    CoordinatePredicate,
    CoordinatePredicateRule,
    ExplicitFaceRule,
    FaceMeasurement,
    FaceSelectionRule,
    FaceSetRule,
    NamedAttributeRule,
    ResolutionSnapshot,
    SelectionRef,
    SelectionValidationError,
    WholeBodyRule,
)
from .solver_policy import (
    SolverControl,
    SolverPolicy,
    SolverPolicyValidationError,
    TimeIncrementPolicy,
)
from .spatial import (
    ORTHOGONALITY_TOLERANCE,
    BodyId,
    Direction3,
    FaceId,
    FrameId,
    GeometryId,
    OpaqueId,
    Point3,
    ProperRotation,
    RigidTransform,
    SpatialValidationError,
    Translation3,
    UnitDirection,
)
from .support import (
    SolidSupport,
    SupportCollection,
    SupportComponent,
    SupportId,
    SupportSet,
    SupportValidationError,
)
from .units import (
    SUPPORTED_UNITS,
    Dimension,
    DimensionMismatchError,
    Quantity,
    UnitDefinition,
    UnitError,
    UnknownUnitError,
    unit_definition,
)

__all__ = [
    "ORTHOGONALITY_TOLERANCE",
    "SCHEMA_VERSION",
    "SUPPORTED_SOURCE_KINDS",
    "SUPPORTED_UNITS",
    "ArrangementIntent",
    "AsPlaced",
    "BodyId",
    "Budget",
    "BudgetValidationError",
    "CanonicalizationError",
    "CompressibleNeoHookean",
    "ContactId",
    "ContactIntent",
    "ContactValidationError",
    "CoordinatePredicate",
    "CoordinatePredicateRule",
    "CoulombFriction",
    "Dimension",
    "DimensionMismatchError",
    "Direction3",
    "DofComponent",
    "DofSpecification",
    "DofState",
    "EvaluationRequest",
    "EvidenceRef",
    "ExplicitFaceRule",
    "FaceId",
    "FaceMeasurement",
    "FaceSelectionRule",
    "FaceSetRule",
    "FrameId",
    "FrictionIntent",
    "Frictionless",
    "GeometryId",
    "GeometryIntent",
    "GeometryValidationError",
    "IsotropicLinearElastic",
    "KinematicCompatibility",
    "LocalRefinement",
    "MaterialApplicability",
    "MaterialCandidate",
    "MaterialValidationError",
    "MeshPolicy",
    "MeshPolicyValidationError",
    "MotionApplicability",
    "MotionCompatibility",
    "MotionProfile",
    "MotionSample",
    "MotionValidationError",
    "NamedAttributeRule",
    "NumericalProfileRef",
    "OpaqueId",
    "OutputPolicy",
    "OutputPolicyValidationError",
    "OutputRequest",
    "Point3",
    "ProperRotation",
    "Quantity",
    "ResolutionSnapshot",
    "RigidDOFComponent",
    "RigidDOFSpecification",
    "RigidDOFState",
    "RigidDofComponent",
    "RigidDofSpecification",
    "RigidDofState",
    "RigidKinematicsValidationError",
    "RigidPrimitive",
    "RigidToolIntent",
    "RigidTransform",
    "RigidValidationError",
    "SelectionRef",
    "SelectionValidationError",
    "SolidSupport",
    "SolverControl",
    "SolverPolicy",
    "SolverPolicyValidationError",
    "SpatialValidationError",
    "SpecifiedGap",
    "SupportCollection",
    "SupportComponent",
    "SupportId",
    "SupportSet",
    "SupportValidationError",
    "TimeIncrementPolicy",
    "Translation3",
    "UnitDefinition",
    "UnitDirection",
    "UnitError",
    "UnknownUnitError",
    "WholeBodyRule",
    "canonical_bytes",
    "check_motion_compatibility",
    "check_translational_indentation_compatibility",
    "unit_definition",
    "validate_translational_indentation_compatibility",
]
