"""P1-A domain contract foundations owned by the common-contract worker."""

from .canonical import SCHEMA_VERSION, CanonicalizationError, canonical_bytes
from .evidence import SUPPORTED_SOURCE_KINDS, EvidenceRef
from .material import (
    CompressibleNeoHookean,
    IsotropicLinearElastic,
    MaterialApplicability,
    MaterialCandidate,
    MaterialValidationError,
)
from .motion import MotionApplicability, MotionProfile, MotionSample, MotionValidationError
from .selection import (
    CoordinatePredicate,
    CoordinatePredicateRule,
    ExplicitFaceRule,
    FaceMeasurement,
    FaceSelectionRule,
    FaceSetRule,
    NamedAttributeRule,
    ResolutionSnapshot,
    SelectionRef,
    SelectionValidationError,
    WholeBodyRule,
)
from .spatial import (
    ORTHOGONALITY_TOLERANCE,
    BodyId,
    Direction3,
    FaceId,
    FrameId,
    GeometryId,
    OpaqueId,
    Point3,
    ProperRotation,
    RigidTransform,
    SpatialValidationError,
    Translation3,
    UnitDirection,
)
from .units import (
    SUPPORTED_UNITS,
    Dimension,
    DimensionMismatchError,
    Quantity,
    UnitDefinition,
    UnitError,
    UnknownUnitError,
    unit_definition,
)

__all__ = [
    "ORTHOGONALITY_TOLERANCE",
    "SCHEMA_VERSION",
    "SUPPORTED_SOURCE_KINDS",
    "SUPPORTED_UNITS",
    "BodyId",
    "CanonicalizationError",
    "CompressibleNeoHookean",
    "CoordinatePredicate",
    "CoordinatePredicateRule",
    "Dimension",
    "DimensionMismatchError",
    "Direction3",
    "EvidenceRef",
    "ExplicitFaceRule",
    "FaceId",
    "FaceMeasurement",
    "FaceSelectionRule",
    "FaceSetRule",
    "FrameId",
    "GeometryId",
    "IsotropicLinearElastic",
    "MaterialApplicability",
    "MaterialCandidate",
    "MaterialValidationError",
    "MotionApplicability",
    "MotionProfile",
    "MotionSample",
    "MotionValidationError",
    "NamedAttributeRule",
    "OpaqueId",
    "Point3",
    "ProperRotation",
    "Quantity",
    "ResolutionSnapshot",
    "RigidTransform",
    "SelectionRef",
    "SelectionValidationError",
    "SpatialValidationError",
    "Translation3",
    "UnitDefinition",
    "UnitDirection",
    "UnitError",
    "UnknownUnitError",
    "WholeBodyRule",
    "canonical_bytes",
    "unit_definition",
]
