"""Headless FEBio solver and synthetic FBS authority boundary."""

from .execution import record_execution_output_artifacts
from .fbs import (
    FbsAdapterAuthority,
    FbsAdapterManager,
    FbsAdapterProtocol,
    FbsValidation,
    validate_requested_fields,
)
from .headless import (
    HeadlessConfigurationError,
    HeadlessReconnectSession,
    HeadlessRunDiagnostic,
    HeadlessRunSession,
    headless_exit_code,
    reconnect_headless_febio,
    recover_headless_febio,
    run_headless_febio,
    run_headless_febio_session,
)
from .log import (
    LogValidation,
    LogValidator,
    NegativeJacobianLogEvidence,
    validate_log,
    validate_solver_log,
)
from .official_fbs import (
    OfficialFbsResultReceipt,
    OfficialFbsRuntime,
    OfficialFbsRuntimeError,
    open_official_fbs_manager,
    probe_official_fbs_runtime,
    require_official_fbs_result,
    validate_official_fbs_runtime,
)
from .runtime import (
    FebioRuntimeDiagnostic,
    RuntimeDiagnostic,
    RuntimeIdentity,
    RuntimeProbeDiagnostic,
    RuntimeProbeError,
    probe_febio,
    probe_runtime,
    validate_runtime_diagnostic,
)
from .studio_fallback import (
    StudioFallbackHandoff,
    StudioFallbackReceipt,
    accept_step_studio_output,
    issue_step_studio_handoff,
)
from .supervisor import SolverSupervisor
from .types import (
    FailureClassification,
    OutputExpectation,
    OutputFreshnessError,
    ProcessState,
    RunState,
    SolverClassification,
    SolverConfigurationError,
    SolverLaunchCapability,
    SolverLaunchError,
    SolverLaunchSpec,
    SolverOwnershipError,
    SolverRunResult,
    SolverState,
)

__all__ = [
    "FailureClassification",
    "HeadlessConfigurationError",
    "HeadlessReconnectSession",
    "HeadlessRunDiagnostic",
    "HeadlessRunSession",
    "FbsAdapterAuthority",
    "FbsAdapterManager",
    "FbsAdapterProtocol",
    "FbsValidation",
    "headless_exit_code",
    "LogValidation",
    "LogValidator",
    "NegativeJacobianLogEvidence",
    "FebioRuntimeDiagnostic",
    "OutputExpectation",
    "OutputFreshnessError",
    "OfficialFbsResultReceipt",
    "OfficialFbsRuntime",
    "OfficialFbsRuntimeError",
    "ProcessState",
    "RunState",
    "SolverClassification",
    "SolverConfigurationError",
    "SolverLaunchCapability",
    "SolverLaunchError",
    "SolverLaunchSpec",
    "SolverOwnershipError",
    "SolverRunResult",
    "SolverState",
    "SolverSupervisor",
    "StudioFallbackHandoff",
    "StudioFallbackReceipt",
    "RuntimeDiagnostic",
    "RuntimeIdentity",
    "RuntimeProbeDiagnostic",
    "RuntimeProbeError",
    "probe_febio",
    "probe_official_fbs_runtime",
    "probe_runtime",
    "require_official_fbs_result",
    "open_official_fbs_manager",
    "record_execution_output_artifacts",
    "recover_headless_febio",
    "reconnect_headless_febio",
    "run_headless_febio",
    "run_headless_febio_session",
    "accept_step_studio_output",
    "issue_step_studio_handoff",
    "validate_log",
    "validate_official_fbs_runtime",
    "validate_requested_fields",
    "validate_runtime_diagnostic",
    "validate_solver_log",
]
